project_id = "ydfqtfutdziejjqnqudo"

[functions.delete-user]
verify_jwt = true

[functions.export-mar]
verify_jwt = true

[functions.export-timesheet]
verify_jwt = true

[functions.generate-report]
verify_jwt = true

[functions.auto-archive-body-logs]
verify_jwt = false

[functions.auto-rollover-tasks]
verify_jwt = false

[functions.auto-cleanup-tasks]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false
